# Generated by Django 2.2.11 on 2020-03-26 08:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Updated date')),
                ('category_name', models.CharField(max_length=255, verbose_name='Category name')),
                ('category_description', models.TextField(verbose_name='Category description')),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='EducationLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=255, unique=True, verbose_name='Education Level')),
                ('description', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'db_table': 'education_level',
            },
        ),
        migrations.CreateModel(
            name='genre_audio_video',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Updated date')),
                ('custom_genre', models.CharField(max_length=255, unique=True, verbose_name='genre name')),
                ('genre_description', models.TextField(blank=True, default='', verbose_name='genre description')),
            ],
            options={
                'db_table': 'custom_genre',
            },
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Updated date')),
                ('keyword', models.CharField(max_length=255, unique=True, verbose_name='Keyword')),
                ('keyword_description', models.TextField(blank=True, default='', verbose_name='Keyword description')),
            ],
            options={
                'db_table': 'keyword',
                'ordering': ['created_date'],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=30, unique=True, verbose_name='Language')),
            ],
            options={
                'db_table': 'language',
            },
        ),
        migrations.CreateModel(
            name='LicenseType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license', models.CharField(max_length=50, null=True, verbose_name='License')),
            ],
            options={
                'db_table': 'tbl_license',
            },
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Updated date')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Sponsor Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'db_table': 'sponsor',
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Updated date')),
                ('publisher_name', models.CharField(max_length=255, unique=True, verbose_name='Publisher name')),
                ('publisher_description', models.TextField(blank=True, null=True, verbose_name='Publisher description')),
                ('publishers_name_in_other_language', models.ManyToManyField(blank=True, related_name='_publisher_publishers_name_in_other_language_+', to='core.Publisher', verbose_name='Publisher(s) name in other language')),
            ],
            options={
                'db_table': 'publisher',
                'ordering': ('publisher_name',),
            },
        ),
        migrations.CreateModel(
            name='Biography',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Updated date')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='First name')),
                ('middle_name', models.CharField(blank=True, max_length=255, verbose_name='Middle name')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Last name')),
                ('name', models.CharField(default='', max_length=255, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('dob', models.CharField(blank=True, max_length=255, null=True, verbose_name='Date of birth')),
                ('place_of_birth', models.CharField(blank=True, default='', max_length=255, verbose_name='Place of birth')),
                ('pen_name', models.CharField(blank=True, max_length=255, verbose_name='Pen name')),
                ('address', models.TextField(blank=True, verbose_name='Address')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='uploads/creator', verbose_name='Creator image')),
                ('place_of_death', models.CharField(blank=True, default='', max_length=255, verbose_name='Place of death')),
                ('date_of_death', models.CharField(blank=True, default='', max_length=255, verbose_name='Date of death')),
                ('authors_name_in_other_language', models.ManyToManyField(blank=True, related_name='_biography_authors_name_in_other_language_+', to='core.Biography', verbose_name='Author(s) name in other language')),
                ('genre', models.ManyToManyField(blank=True, to='core.genre_audio_video', verbose_name='Genre')),
                ('keywords', models.ManyToManyField(blank=True, to='core.Keyword', verbose_name='Search Keywords')),
            ],
            options={
                'verbose_name': 'Author',
                'db_table': 'biography',
                'ordering': ['first_name'],
            },
        ),
    ]
